services:

  hck-fetch-test-proxy:
    image: hackolade.azurecr.io/squid-proxy:latest
    init: true
    entrypoint: /apps/squid/sbin/squid
    command: --foreground
    ports:
      - 3128:3128
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-exec',
          'curl -sSL --fail -x localhost:3128 https://google.com',
        ]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s

  hck-fetch-test-server: 
    build:
      context: .
      dockerfile: Dockerfile
      target: hck-fetch-test-server
    init: true
    expose:
      - 3000
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-exec',
          'curl -sSL --fail localhost:3000/status',
        ]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s
    depends_on:
      hck-fetch-test-proxy:
        condition: service_healthy

  hck-fetch-test-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: hck-fetch-test-app
    init: true
    network_mode: host 
    environment:
      - HTTP_PROXY=localhost:3128
      - HTTPS_PROXY=localhost:3128
    depends_on:
      hck-fetch-test-server:
        condition: service_healthy
      hck-fetch-test-proxy:
        condition: service_healthy

#  tests: 
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: hck-fetch-tests
#    init: true
#    depends_on:
#      hck-fetch-test-app:
#        condition: service_completed_successfully
