# See https://docs.npmjs.com/trusted-publishers
name: Release library

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - name: Install NPM dependencies
        run: npm ci
      - name: Publish library to NPM registry
        run: npm publish
      - name: Extract package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.package-version.outputs.current-version}}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
